// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChUJTNxdaaiLgPegO9v4ZLZmj5MDAXMsU',
    appId: '1:1096609200976:web:747f7d1dc72b7b13e18a55',
    messagingSenderId: '1096609200976',
    projectId: 'project2-e688a',
    authDomain: 'project2-e688a.firebaseapp.com',
    storageBucket: 'project2-e688a.firebasestorage.app',
    measurementId: 'G-1CV7WHPXTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXPFHkmDM7iLXPFol9IfdJ2iaI65NNvk',
    appId: '1:1096609200976:android:379cfb7e4d3b2c18e18a55',
    messagingSenderId: '1096609200976',
    projectId: 'project2-e688a',
    storageBucket: 'project2-e688a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-RNjGv_2463FD_ZvT8ockmkOlsuZ78g8',
    appId: '1:1096609200976:ios:e114acc159b18529e18a55',
    messagingSenderId: '1096609200976',
    projectId: 'project2-e688a',
    storageBucket: 'project2-e688a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-RNjGv_2463FD_ZvT8ockmkOlsuZ78g8',
    appId: '1:1096609200976:ios:e114acc159b18529e18a55',
    messagingSenderId: '1096609200976',
    projectId: 'project2-e688a',
    storageBucket: 'project2-e688a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChUJTNxdaaiLgPegO9v4ZLZmj5MDAXMsU',
    appId: '1:1096609200976:web:101530cdef8749eae18a55',
    messagingSenderId: '1096609200976',
    projectId: 'project2-e688a',
    authDomain: 'project2-e688a.firebaseapp.com',
    storageBucket: 'project2-e688a.firebasestorage.app',
    measurementId: 'G-GC8NNH1EDV',
  );

}